### ISSUE TITLE
collection_quickies.py

### ISSUE THREAD

**Issue by youthatninja** [venomgfx/addonitos#3]
Traceback (most recent call last):
  File "e:\Desktop\blender-2.80.0-git.84c06e996a7a-windows64\2.80\scripts\modules\addon_utils.py", line 377, in enable
    raise Exception(f"Add-on '{module_name:s}' has not been upgraded to 2.8, ignoring")
Exception: Add-on 'collection_quickies' has not been upgraded to 2.8, ignoring

**Comment by schroef** [comment]
simply add 2,80,0

**Comment by youthatninja** [comment]
@schroef yeah, i figure it out after i started issue)

**Comment by schroef** [comment]
BUt i dont understand this addon, i think its not working properly. It will also add dots for all objects. Not only for collections. Thats doesnt seem like its function. Also what happens with more 20, will it keep adding a old layer style with dots. Currently there is also an issue than addded dots go off screen, not reachable for the mouse. Than at some point, havent figured out exactly when, you can scroll to the most right side. 

I think this addon will work better if is added to a panel. Its making the top bar quite wide really fast
